# Helpful key bindings
source-file ~/.config/tmux/bindings.conf

set-option -g default-terminal 'tmux-256color'
set-option -g terminal-overrides ',xterm-256color:RGB'

set -g prefix ^A
set -g base-index 1              # start indexing windows at 1 instead of 0
set -g mouse on                  # use mouse to resize panes
set -g detach-on-destroy off     # don't exit from tmux when closing a session
set -g escape-time 0             # zero-out escape time delay
set -g history-limit 9000        # increase history size (from 2,000)
set -g renumber-windows on       # renumber all windows when any window is closed
set -g set-clipboard on          # use system clipboard
set -g status-position top       # macOS / darwin style
set -g default-terminal "${TERM}"
setw -g mode-keys vi
set -g pane-active-border-style 'fg=green,bg=default'
set -g pane-border-style 'fg=brightblack,bg=default'

# set -g @fzf-url-fzf-options '-p 60%,30% --prompt="   " --border-label=" Open URL "'
# set -g @fzf-url-history-limit '9000'

set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'
# set -g @plugin 'fcsonline/tmux-thumbs'
# set -g @plugin 'sainnhe/tmux-fzf'
# set -g @plugin 'wfxr/tmux-fzf-url'

# Floax
# source-file ~/.config/tmux/floax.conf

# Sessionx
# source-file ~/.config/tmux/sessionx.conf

# set -g @continuum-restore 'on'
# set -g @resurrect-strategy-nvim 'session'

# Gruvbox theme configuration - (Not working for some reason)
# source-file ~/.config/tmux/gruvbox.conf

# Catppuccin theme configuration
source-file ~/.config/tmux/catppuccin.conf

run '~/.config/tmux/plugins/tpm/tpm'
# set -g status-bg default
set -g status-style bg=default
