set -g @plugin 'egel/tmux-gruvbox'

set -g @tmux-gruvbox 'dark256'

# Transparent status bar
set -g @tmux-gruvbox-statusbar-alpha 'true'

# Left status - A
set -g @tmux-gruvbox-left-status-a ''

# Right status - X, Y, Z
set -g @tmux-gruvbox-right-status-x ''
set -g @tmux-gruvbox-right-status-y '#S'
set -g @tmux-gruvbox-right-status-z '#S'
